language: node_js
node_js:
  - 16.9
os: linux
arch:
  - amd64
#  - arm64

branches:
  only:
    - main

stages:

services:
  - docker

script:
  - docker build -t "$DOCKER_IMAGE_NAME" .
  - docker tag "$DOCKER_IMAGE_NAME" "$DOCKER_IMAGE_NAME":latest
  - docker tag "$DOCKER_IMAGE_NAME" "$DOCKER_IMAGE_NAME":git-"$TRAVIS_BRANCH"
  - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE_NAME":git-"$TRAVIS_BRANCH"
  - docker push "$DOCKER_IMAGE_NAME":"latest"
